import React from 'react';
import { format, parseISO, addDays } from 'date-fns';

const formatTime = (timeStr) => {
  if (!timeStr) return 'N/A';
  const [h, m] = timeStr.split(':').map(Number);
  const d = new Date();
  d.setHours(h);
  d.setMinutes(m);
  return d.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
  });
};

const PrintableLaborSchedule = ({ scheduleData, weekStartDate }) => {
  if (!scheduleData) return <p className="text-center p-4">Loading printable schedule...</p>;

  const weekDates = Array.from({ length: 7 }, (_, i) => format(addDays(weekStartDate, i), 'yyyy-MM-dd'));

  return (
    <div className="printable-labor-schedule-container p-4" style={{ fontSize: '11px', lineHeight: '1.4' }}>
      <style>{`
        @media print {
          @page { size: landscape; }
          .avoid-break { page-break-inside: avoid; break-inside: avoid; }
          table { border-collapse: collapse; width: 100%; }
          th, td { border: 1px solid #ccc; padding: 2px 6px; }
          .print-footer { text-align: center; font-size: 10px; color: #999; margin-top: 1rem; }
        }
      `}</style>

      <div className="print-header text-center mb-6">
        <h1 className="app-title text-2xl font-bold">Weekly Labor Schedule</h1>
        <p className="print-date text-sm">
          Week of: {format(weekStartDate, 'MMMM dd, yyyy')} - {format(addDays(weekStartDate, 6), 'MMMM dd, yyyy')}
        </p>
      </div>

      {weekDates.map(date => {
        const daySlots = scheduleData[date] || [];

        // Group by shift and role
        const grouped = {};
        daySlots.forEach(slot => {
          const { shift = 'N/A', role = 'Unassigned' } = slot;
          if (!grouped[shift]) grouped[shift] = {};
          if (!grouped[shift][role]) grouped[shift][role] = [];
          grouped[shift][role].push(slot);
        });

        return (
          <div key={date} className="daily-schedule avoid-break mb-6">
            <h2 className="daily-schedule-title text-lg font-semibold border-b pb-1 mb-2">
              {format(parseISO(date), 'EEEE, MMMM dd, yyyy')}
            </h2>

            {Object.keys(grouped).length > 0 ? (
              Object.entries(grouped).map(([shiftType, roles]) => (
                <div key={shiftType} className="mb-3">
                  <h3 className="text-md font-medium capitalize mb-1">{shiftType} Shift</h3>
                  <table className="table-print">
                    <thead>
                      <tr>
                        <th className="text-left text-xs">Role</th>
                        <th className="text-left text-xs">Employee</th>
                        <th className="text-left text-xs">Time</th>
                      </tr>
                    </thead>
                    <tbody>
                      {Object.entries(roles).map(([roleName, employees]) =>
                        employees.map((slot, index) => (
                          <tr key={`${roleName}-${index}`}>
                            <td className="text-xs">{index === 0 ? roleName : ''}</td>
                            <td className="text-xs">
                              {slot.employeeName || <em className="text-gray-500">Unassigned</em>}
                            </td>
                            <td className="text-xs">
                              {formatTime(slot.startTime)} – {formatTime(slot.endTime)}
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              ))
            ) : (
              <p className="text-xs italic">No shifts scheduled for this day.</p>
            )}
          </div>
        );
      })}

      {/* Optional footer */}
      {/* <div className="print-footer">Generated by Mopped OS — Smoked slow. Served fast.</div> */}
    </div>
  );
};

export default PrintableLaborSchedule;
